<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SonarQubeExclude>true</SonarQubeExclude>
    <RootNamespace>StableFPSRecorder</RootNamespace>
    <AssemblyName>StableFPSRecorder</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
    <PackageReference Include="MilestoneSystems.VideoOS.Platform.SDK.Core" Version="1.2.0" />
  </ItemGroup>

</Project>
