<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>sdk_core_crud</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <!-- TODO: change reference -->
    <PackageReference Include="MilestoneSystems.VideoOS.Platform.SDK.Core" Version="1.0.0" />
  </ItemGroup>
	
</Project>
